import unpack as up
import calibration as cal
import numpy as np
import matplotlib.pyplot as plt

c = cal.Calibrate(up.Unpack())
pixels = np.arange(2048)
deg1 = c.wavelength_fit(degree=1)
deg2 = c.wavelength_fit(degree=2)
deg3 = c.wavelength_fit(degree=3)

plt.figure(1)
cal.plot_peaks(c.neon, c.neon_centroids)
cal.plot_peaks(c.mercury, c.mercury_centroids)
plt.xlabel("Pixel Number")
plt.ylabel("Intensity")
plt.title("Measured Spectra for Ne and Hg with peaks")
plt.figure(2)
plt.subplot(311)
plt.plot(c.neon_centroids, cal.NEON_PEAKS, 'o', color='blue')
plt.plot(c.mercury_centroids, cal.MERCURY_PEAKS, 'o', color='blue')
plt.plot(pixels, deg1, '--')
plt.plot(pixels, deg2, '--')
plt.plot(pixels, deg3)
plt.xlabel("Pixel")
plt.ylabel("Wavelength (A)")
plt.title("Wavelength Solution to Spectrometer")
plt.subplot(312)
plt.plot(pixels, deg2 - deg1)
plt.xlabel("Pixel")
plt.ylabel("Difference (A)")
plt.title("(2rd Degree - 1nd Degree) fit comparison")
plt.subplot(313)
plt.plot(pixels, deg3 - deg2)
plt.xlabel("Pixel")
plt.ylabel("Difference (A)")
plt.title("(3rd Degree - 2nd Degree) fit comparison")
plt.tight_layout()
plt.show()
